/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CapitalVerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getMyCapital"
      | "getMyVerificationResult"
      | "getUserSubmissionTime"
      | "hasSubmitted"
      | "hasUserSubmitted"
      | "submissionTimestamp"
      | "submitCapital"
      | "userCapital"
      | "verificationResults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CapitalSubmitted" | "VerificationCompleted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyCapital",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyVerificationResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSubmissionTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submissionTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitCapital",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userCapital",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationResults",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyVerificationResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSubmissionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissionTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationResults",
    data: BytesLike
  ): Result;
}

export namespace CapitalSubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationCompletedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CapitalVerification extends BaseContract {
  connect(runner?: ContractRunner | null): CapitalVerification;
  waitForDeployment(): Promise<this>;

  interface: CapitalVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMyCapital: TypedContractMethod<[], [string], "view">;

  getMyVerificationResult: TypedContractMethod<[], [string], "view">;

  getUserSubmissionTime: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  hasSubmitted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasUserSubmitted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  submissionTimestamp: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  submitCapital: TypedContractMethod<
    [encryptedCapital: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  userCapital: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  verificationResults: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyCapital"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyVerificationResult"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getUserSubmissionTime"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasUserSubmitted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submissionTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitCapital"
  ): TypedContractMethod<
    [encryptedCapital: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userCapital"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "verificationResults"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "CapitalSubmitted"
  ): TypedContractEvent<
    CapitalSubmittedEvent.InputTuple,
    CapitalSubmittedEvent.OutputTuple,
    CapitalSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationCompleted"
  ): TypedContractEvent<
    VerificationCompletedEvent.InputTuple,
    VerificationCompletedEvent.OutputTuple,
    VerificationCompletedEvent.OutputObject
  >;

  filters: {
    "CapitalSubmitted(address,uint256)": TypedContractEvent<
      CapitalSubmittedEvent.InputTuple,
      CapitalSubmittedEvent.OutputTuple,
      CapitalSubmittedEvent.OutputObject
    >;
    CapitalSubmitted: TypedContractEvent<
      CapitalSubmittedEvent.InputTuple,
      CapitalSubmittedEvent.OutputTuple,
      CapitalSubmittedEvent.OutputObject
    >;

    "VerificationCompleted(address,uint256)": TypedContractEvent<
      VerificationCompletedEvent.InputTuple,
      VerificationCompletedEvent.OutputTuple,
      VerificationCompletedEvent.OutputObject
    >;
    VerificationCompleted: TypedContractEvent<
      VerificationCompletedEvent.InputTuple,
      VerificationCompletedEvent.OutputTuple,
      VerificationCompletedEvent.OutputObject
    >;
  };
}
